### ISSUE TITLE
Release Checklist (`v0.0.1`)

### ISSUE THREAD

**Issue by dgkf** [dgkf/options#1]
# Release `v0.0.1`

### Checklist

- [x] `NEWS` is up-to-date
- [x] Bump `DESCRIPTION` version
- [x] Create merge request with changes
- [x] Publish to CRAN
- [x] Merge changes
- [x] Tag release commit with version number (`v0.0.0`)
- [x] GitHub release
- [x] Introduce commit to add dev version number
